config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "admin"

  root 'welcome#index'

  resources :profiles, path: "about"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_presence :picture
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  process_in_background :picture
  validates :name,
            :position,
            :biography, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find params[:id]
  end

  def new
    @profile = Profile.new
  end

  def edit
    @profile = Profile.find params[:id]
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profiles_path
    else
      render :new
      flash[:notice] = "Profile not created"
    end
  end

  def update
    @profile = Profile.find params[:id]
    @profile.update(profile_params)

    if @profile.save
      redirect_to profiles_path
    else
      render :edit
    end
  end

  def destroy
    @profile = Profile.find params[:id]
    @profile.destroy
    redirect_to profiles_path
  end

private

  def profile_params
    params.require(:profile).permit!
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index 
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Hotel For Dads" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<header class="hfd-header">
  		<nav class="desktop-nav">
  			<div class="left-nav cl-effect-11">
  				<a href="/about/" data-hover="ABOUT">ABOUT</a>
  				<a href="" data-hover="ARCHIVE">ARCHIVE</a>
  			</div>
  			<a href="/" class="logo">
  				<h1 class="large-text" data-hover="hotel">hotel</h1>
  				<h2 class="for">for</h2>

  				<h1 class="large-text" style="font-size:52px;" data-hover="dads">dads</h1>
  			</a>
  			<div class="right-nav cl-effect-11">
  				<a href="" data-hover="CONTACT">CONTACT</a>
           <%= render 'devise/shared/log_out' %>
  			</div>
  		</nav>

  	</header>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

    <%= yield %>

  </body>
</html>

app/views/profiles/_form.html.erb
<% if @profile.errors.any? %>
  <ul>
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<div class = "row">
  <div class="small-12 columns">
    <%= form_for @profile, html: { multipart: true } do |f| %>
      <%= f.file_field :picture %>
      <%= f.text_field :name, placeholder: "NAME" %>
      <%= f.text_field :position, placeholder: "POSITION" %>
      <%= f.text_area :biography, placeholder: "BIOGRAPHY" %>
      <%= f.text_field :facebook_url %>
      <%= f.text_field :instagram_url %>
      <%= f.text_field :twitter_url %>
      <%= f.text_field :youtube_url %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<section id="ps-container" class="ps-container">

	<!-- <div class="ps-header">
		<h1>Vertical Showcase Slider</h1>
	</div><!-- /ps-header -->			

	
	<div class="ps-slidewrapper">

		<% @profiles.each do |profile| %>
	
		<%= div_for profile, class:"ps-slides" do %>

			<div style="background-image:url(<%= profile.picture.url %>)" class="main-slide-image"></div>

		<% end %>

		<% end %>
		
		<nav>
			<a href="#" class="ps-prev" ></a>
			<a href="#" class="ps-next" ></a>
		</nav>
		
	</div><!-- /ps-slidewrapper -->


	<div class="ps-contentwrapper">

		<% @profiles.each do |profile| %>
	
			<%= div_for profile, class: "ps-content" do %>
				<%= content_tag_for(:h2, profile) do %>
					<%= profile.name %>
				<% end %>
				<%= content_tag_for(:span, profile, class: "ps-price") do %>
					<%= profile.position %>
				<% end %>
				<%= content_tag_for(:p, profile) do %>
					<%= profile.biography %>
					<%= link_to "Edit", edit_profile_path(profile) %>
					<%= link_to "Delete", profile_path(profile), method: :delete %>
				<% end %>
			<% end %>
		<% end %>
		
	</div><!-- /ps-contentwrapper -->
	
</section><!-- /ps-container -->

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/shared/_navbar.html.erb
<header class="hfd-header">
  <nav class="desktop-nav">
    <div class="left-nav">
      <a href="">ABOUT</a>
      <a href="">ARCHIVE</a>
    </div>
    <div class="logo">
      <h1 class="large-text">hotel</h1>
      <h2 class="for">for</h2>
      <h1 class="large-text">dads</h1>
    </div>
    <div class="right-nav">
      <a href="">CONTACT</a>
      <%= render 'devise/shared/log_out' %>
    </div>
  </nav>
</header>

app/views/welcome/index.html.erb
<%= render 'devise/shared/log_out' %>

	<div class="hero-vid">
		<div class="overlay"></div>
	</div>